---
version: '3'
services:
  portfolio:
    image: jitesoft/lighttpd:1.4.73
    container_name: server
    ports: [7000:80]
    volumes:
      - ./src:/var/www/html
      - ./lighttpd.conf:/etc/lighttpd/conf.d/000-mime.conf

  # livereload:
  #   image: harianto/livereload
  #   container_name: livereloader
  #   ports:
  #     - "35729:35729"
  #   volumes:
  #     - ./src:/usr/src/livereload-watch
